package ui.Client;

import resort.EcoSystem;
import resort.Laundry.Laundry;
import resort.User.User;
import resort.RolesCD.LaundryRequest;
import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.MutableComboBoxModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arvin
 */
public class ClientLaundryBooking extends javax.swing.JPanel {

    /**
     * Creates new form ClientLaundryBooking
     */
    EcoSystem system;
    User user;

    public ClientLaundryBooking(EcoSystem system, User user) {
        initComponents();

        this.system = system;
        this.user = user;

        MutableComboBoxModel<String> model = new DefaultComboBoxModel<String>();

        for (Laundry laundryList : system.getLaundryDirectory().getLaundryDirectory()) {
            model.addElement(laundryList.getLaundryCategory());
        }

        chooseLaundryDropdown.setModel(model);

        categoryNameTxt.setEditable(false);
        priceTxt.setEditable(false);

        populateRequestTable();
        formatRows();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        priceTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        categoryNameTxt = new javax.swing.JTextField();
        numberOfClothesTxt = new javax.swing.JTextField();
        bookLaundryBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        laundryWorkQueueTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        viewPriceBtn = new javax.swing.JButton();
        chooseLaundryDropdown = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Laundry Booking Status");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Catergory Name:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Enter Number of clothes:");

        bookLaundryBtn.setBackground(new java.awt.Color(0, 102, 102));
        bookLaundryBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bookLaundryBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookLaundryBtn.setText("Book Laundry");
        bookLaundryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookLaundryBtnActionPerformed(evt);
            }
        });

        laundryWorkQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category Name", "Price per cloth", "Number of clothes", "Total price", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(laundryWorkQueueTable);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Book Laundry");

        viewPriceBtn.setBackground(new java.awt.Color(0, 102, 102));
        viewPriceBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        viewPriceBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewPriceBtn.setText("View Price");
        viewPriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPriceBtnActionPerformed(evt);
            }
        });

        chooseLaundryDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLaundryDropdownActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Price per cloth:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Choose a category of your choice:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Images_R/laund.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberOfClothesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseLaundryDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookLaundryBtn)
                                    .addComponent(jLabel9))))
                        .addGap(40, 40, 40)
                        .addComponent(viewPriceBtn)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(399, 399, 399))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {categoryNameTxt, chooseLaundryDropdown, numberOfClothesTxt, priceTxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chooseLaundryDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(viewPriceBtn))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(numberOfClothesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bookLaundryBtn))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {categoryNameTxt, chooseLaundryDropdown, numberOfClothesTxt, priceTxt});

    }// </editor-fold>//GEN-END:initComponents

    private void bookLaundryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookLaundryBtnActionPerformed
        // Book a vehicle after entering details
        LaundryRequest bookLaundry = new LaundryRequest();

        try {
            if (chooseLaundryDropdown.getSelectedItem() != null) {
                String laundryName = String.valueOf(chooseLaundryDropdown.getSelectedItem());
                Laundry laundryDetails = system.getLaundryDirectory().getLaundryByName(laundryName);
                int numberOfClothes = Integer.parseInt(numberOfClothesTxt.getText());

                bookLaundry.setSelectedLaundry(laundryDetails);
                bookLaundry.setClothesCount(numberOfClothes);
                bookLaundry.setUserId(user.getUserId());
                bookLaundry.setOrderStatus("Pending");

                system.getLaundryRequestDirectory().getLaundryRequestList().add(bookLaundry);

                JOptionPane.showMessageDialog(this, "Laundry booking request sent to Manager");
                populateRequestTable();
                clearFields();
                formatRows();

            } else {
                JOptionPane.showMessageDialog(this, "Enter valid number of clothes values for booking Laundry");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter valid number of clothes values for booking Laundry");
        }
    }//GEN-LAST:event_bookLaundryBtnActionPerformed

    private void viewPriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPriceBtnActionPerformed
        // View Vehicle Details on choosing

        try {
            if (chooseLaundryDropdown.getSelectedItem() != null) {

                String laundryName = String.valueOf(chooseLaundryDropdown.getSelectedItem());
                Laundry laundryDetails = system.getLaundryDirectory().getLaundryByName(laundryName);

                categoryNameTxt.setText(laundryDetails.getLaundryCategory());
                priceTxt.setText(String.valueOf(laundryDetails.getLaundryPrice()));

            } else {
                JOptionPane.showMessageDialog(this, "Choose a valid Laundry category for booking");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Choose a valid Laundry category for booking");
        }
    }//GEN-LAST:event_viewPriceBtnActionPerformed

    private void chooseLaundryDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLaundryDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseLaundryDropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookLaundryBtn;
    private javax.swing.JTextField categoryNameTxt;
    private javax.swing.JComboBox<String> chooseLaundryDropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable laundryWorkQueueTable;
    private javax.swing.JTextField numberOfClothesTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton viewPriceBtn;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {

        try {
            DefaultTableModel model = (DefaultTableModel) laundryWorkQueueTable.getModel();
            model.setRowCount(0);

            for (LaundryRequest laundryWorkRequest : system.getLaundryRequestDirectory().getLaundryRequestList()) {

                if (laundryWorkRequest.getUserId().equals(user.getUserId())) {
                    Object[] newRow = new Object[5];
                    newRow[0] = laundryWorkRequest.getSelectedLaundry().getLaundryCategory();
                    newRow[1] = laundryWorkRequest.getSelectedLaundry().getLaundryPrice();
                    newRow[2] = laundryWorkRequest.getClothesCount();
                    newRow[3] = (laundryWorkRequest.getSelectedLaundry().getLaundryPrice() * laundryWorkRequest.getClothesCount());
                    newRow[4] = laundryWorkRequest.getOrderStatus();

                    model.addRow(newRow);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearFields() {

        categoryNameTxt.setText("");
        priceTxt.setText("");
        numberOfClothesTxt.setText("");

    }
    
    private void formatRows() {

        DefaultTableModel model = (DefaultTableModel) laundryWorkQueueTable.getModel();

        laundryWorkQueueTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = String.valueOf(model.getValueAt(row, 4));
                c.setBackground(status.equals("Pending") ? Color.WHITE : status.equals("Approved") ? Color.GREEN : Color.RED);
                return c;
            }
        });

    }
}
