package ui.Client;

import resort.EcoSystem;
import resort.User.User;

/**
 *
 * @author arvin
 */
public class ClientHome extends javax.swing.JPanel {

    /**
     * Creates new form CustomerHome
     */
    
    EcoSystem system;
    User user;
    
    public ClientHome(EcoSystem system, User user) {
        initComponents();
        this.system = system;
        this.user = user;
        initializeUserData();
        
//        jLabel3.setText(user.getFirstName() + " " + user.getLastName());
    }
    
    private void initializeUserData() {
        jLabel3.setText(user.getFirstName() + " " + user.getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userLeftPanel = new javax.swing.JPanel();
        bookVehicleBtn = new javax.swing.JButton();
        bookPoolBtn = new javax.swing.JButton();
        bookGameBtn = new javax.swing.JButton();
        bookLaundryBtn = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        bookFoodBtn = new javax.swing.JButton();
        userRightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        userLeftPanel.setBackground(new java.awt.Color(255, 255, 255));

        bookVehicleBtn.setBackground(new java.awt.Color(0, 102, 102));
        bookVehicleBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bookVehicleBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookVehicleBtn.setText("Book Transport");
        bookVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookVehicleBtnActionPerformed(evt);
            }
        });

        bookPoolBtn.setBackground(new java.awt.Color(0, 102, 102));
        bookPoolBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bookPoolBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookPoolBtn.setText("Book SwimmingPool");
        bookPoolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPoolBtnActionPerformed(evt);
            }
        });

        bookGameBtn.setBackground(new java.awt.Color(0, 102, 102));
        bookGameBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bookGameBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookGameBtn.setText("Book Games");
        bookGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookGameBtnActionPerformed(evt);
            }
        });

        bookLaundryBtn.setBackground(new java.awt.Color(0, 102, 102));
        bookLaundryBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bookLaundryBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookLaundryBtn.setText("Book Laundry");
        bookLaundryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookLaundryBtnActionPerformed(evt);
            }
        });

        checkOutBtn.setBackground(new java.awt.Color(0, 102, 102));
        checkOutBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        checkOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkOutBtn.setText("Payment");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        bookFoodBtn.setBackground(new java.awt.Color(0, 102, 102));
        bookFoodBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bookFoodBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookFoodBtn.setText("Book Food Items");
        bookFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFoodBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLeftPanelLayout = new javax.swing.GroupLayout(userLeftPanel);
        userLeftPanel.setLayout(userLeftPanelLayout);
        userLeftPanelLayout.setHorizontalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(bookVehicleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookGameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookLaundryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookPoolBtn)
                    .addComponent(checkOutBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        userLeftPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bookFoodBtn, bookGameBtn, bookLaundryBtn, bookPoolBtn, bookVehicleBtn});

        userLeftPanelLayout.setVerticalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(bookVehicleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookPoolBtn)
                .addGap(18, 18, 18)
                .addComponent(bookGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookLaundryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );

        userLeftPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bookFoodBtn, bookGameBtn, bookLaundryBtn, bookPoolBtn, bookVehicleBtn});

        jSplitPane1.setLeftComponent(userLeftPanel);

        userRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        userRightPanel.setForeground(new java.awt.Color(0, 102, 102));
        userRightPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Customer Home Panel");
        userRightPanel.add(jLabel1);
        jLabel1.setBounds(240, 50, 360, 29);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Welcome to the Customer Panel");
        userRightPanel.add(jLabel2);
        jLabel2.setBounds(230, 140, 350, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userRightPanel.add(jLabel3);
        jLabel3.setBounds(550, 190, 240, 40);

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Choose a facility to use from the sidebar.");
        userRightPanel.add(jLabel4);
        jLabel4.setBounds(250, 170, 215, 22);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Images_R/room.jpg"))); // NOI18N
        userRightPanel.add(jLabel5);
        jLabel5.setBounds(100, 130, 550, 430);

        jSplitPane1.setRightComponent(userRightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookVehicleBtnActionPerformed
        // Redirect User to Vehicle Booking Panel
        ClientTransportationBooking bookVehicle = new ClientTransportationBooking(system, user);
        jSplitPane1.setRightComponent(bookVehicle);
    }//GEN-LAST:event_bookVehicleBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
        ClientCheckout checkout = new ClientCheckout(system, user);
        jSplitPane1.setRightComponent(checkout);
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void bookFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFoodBtnActionPerformed
        // TODO add your handling code here:
        ClientFoodBooking bookFood = new ClientFoodBooking(system, user);
        jSplitPane1.setRightComponent(bookFood);
    }//GEN-LAST:event_bookFoodBtnActionPerformed

    private void bookPoolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPoolBtnActionPerformed
        // TODO add your handling code here:
        ClientPoolBooking bookPool = new ClientPoolBooking(system, user);
        jSplitPane1.setRightComponent(bookPool);
    }//GEN-LAST:event_bookPoolBtnActionPerformed

    private void bookGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookGameBtnActionPerformed
        // TODO add your handling code here:
        ClientGameBooking bookGame = new ClientGameBooking(system, user);
        jSplitPane1.setRightComponent(bookGame);
    }//GEN-LAST:event_bookGameBtnActionPerformed

    private void bookLaundryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookLaundryBtnActionPerformed
        // TODO add your handling code here:
        ClientLaundryBooking bookLaundry = new ClientLaundryBooking(system, user);
        jSplitPane1.setRightComponent(bookLaundry);
    }//GEN-LAST:event_bookLaundryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookFoodBtn;
    private javax.swing.JButton bookGameBtn;
    private javax.swing.JButton bookLaundryBtn;
    private javax.swing.JButton bookPoolBtn;
    private javax.swing.JButton bookVehicleBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userLeftPanel;
    private javax.swing.JPanel userRightPanel;
    // End of variables declaration//GEN-END:variables
}
