package ui.Game;

import resort.EcoSystem;
import resort.Email.EmailAlert;
import resort.Client.TransactionHistory.ClientTransaction;
import resort.User.User;
import resort.RolesCD.GameRequest;
import resort.RolesCD.TransportRequest;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arvin
 */
public class ManageGameRequests extends javax.swing.JPanel {
     EcoSystem system;

    /**
     * Creates new form ManageGameRequestsPanel
     */
    public ManageGameRequests(EcoSystem system) {
        initComponents();
        
        this.system = system;
        populateGameRequestTable();
        formatRows();
        
    }
    
    public void populateGameRequestTable() {
        ArrayList<GameRequest> pendingGameRequest = new ArrayList<GameRequest>();
        ArrayList<GameRequest> non_pendingGameRequest = new ArrayList<GameRequest>();

        for (GameRequest gameWRequest : system.getGameRequestDirectory().getGameRequestList()) {
            if (gameWRequest.getBookingStatus().equals("Pending")) {
                pendingGameRequest.add(gameWRequest);
            } else {
                non_pendingGameRequest.add(gameWRequest);
            }
        }

        populate_based_on_status(pendingGameRequest, non_pendingGameRequest);
    }

    public void populate_based_on_status(ArrayList<GameRequest> pendingGameRequest, ArrayList<GameRequest> non_pendingGameRequest) {
        DefaultTableModel model = (DefaultTableModel) tblGameRequests.getModel();
        model.setRowCount(0);
        for (GameRequest gameWRequest : pendingGameRequest) {

            Object[] newRow = new Object[7];
            newRow[0] = gameWRequest;
            newRow[1] = gameWRequest.getSelectedGame().getGameTitle();
            newRow[2] = gameWRequest.getSelectedGame().getGameGenre();
            newRow[3] = gameWRequest.getSelectedGame().getCost();
            newRow[4] = gameWRequest.getDurationInHours();
            newRow[5] = gameWRequest.getReservationDate();
            newRow[6] = gameWRequest.getBookingStatus();

            model.addRow(newRow);
        }

        DefaultTableModel modelNon_Pending = (DefaultTableModel) tblGameConfirmed.getModel();
        modelNon_Pending.setRowCount(0);
        for (GameRequest gameWRequest : non_pendingGameRequest) {

            Object[] newRow = new Object[7];
            newRow[0] = gameWRequest;
            newRow[1] = gameWRequest.getSelectedGame().getGameTitle();
            newRow[2] = gameWRequest.getSelectedGame().getGameGenre();
            newRow[3] = gameWRequest.getSelectedGame().getCost();
            newRow[4] = gameWRequest.getDurationInHours();
            newRow[5] = gameWRequest.getReservationDate();
            newRow[6] = gameWRequest.getBookingStatus();

            modelNon_Pending.addRow(newRow);
        }

    }
    
    public void updateWorkRequestStatus(GameRequest selectedGame, String status) {
        selectedGame.setBookingStatus(status);
        int index = 0;
        for (GameRequest gameWRequest : system.getGameRequestDirectory().getGameRequestList()) {
            if (gameWRequest.getUserId().equals(selectedGame.getUserId())) {
                system.getGameRequestDirectory().updateGameRequest(gameWRequest, index);
                break;
            }
            index++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGameRequests = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGameConfirmed = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE REQUESTS");

        tblGameRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Game Name", "Category", "Price per hour($)", "No. of Hours", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGameRequests);

        tblGameConfirmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Game Name", "Category", "Price per hour($)", "No. of Hours", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblGameConfirmed);

        btnApprove.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(0, 102, 102));
        btnApprove.setText("APPROVE");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnReject.setForeground(new java.awt.Color(0, 102, 102));
        btnReject.setText("REJECT");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(btnApprove)
                        .addGap(66, 66, 66)
                        .addComponent(btnReject))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApprove, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReject))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
         try {
            int selectedRowIndex = tblGameRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to approve.");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) tblGameRequests.getModel();
            GameRequest selectedGameWorkRequest = (GameRequest) model.getValueAt(selectedRowIndex, 0);
            updateWorkRequestStatus(selectedGameWorkRequest, "Approved");
            ClientTransaction ct = new ClientTransaction();
            
            //User definition for email notif
            User getUser = system.getUserDirectory().getUserById(selectedGameWorkRequest.getUserId());

            float gamebooking_finalprice = selectedGameWorkRequest.getDurationInHours() * selectedGameWorkRequest.getSelectedGame().getCost();
            ct.setUserId(selectedGameWorkRequest.getUserId());
            ct.setSelectedCenter("Game Booked - " + selectedGameWorkRequest.getSelectedGame().getGameTitle() + " for " + selectedGameWorkRequest.getDurationInHours() + " hours");
            ct.setTotalCost(gamebooking_finalprice);
            system.getClientTransactionDirectory().addClientTransaction(ct);
            
             //email notification
            new EmailAlert().SendEmailOfNotification(getUser, "Game");
            
            JOptionPane.showMessageDialog(this, "Request approved successfully and email notification sent");
            populateGameRequestTable();
            formatRows();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
         try {
            int selectedRowIndex = tblGameRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to approve.");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) tblGameRequests.getModel();
            GameRequest selectedGameWorkRequest = (GameRequest) model.getValueAt(selectedRowIndex, 0);
            updateWorkRequestStatus(selectedGameWorkRequest, "Rejected");
            JOptionPane.showMessageDialog(this, "Request rejected successfully");
            populateGameRequestTable();
            formatRows();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGameConfirmed;
    private javax.swing.JTable tblGameRequests;
    // End of variables declaration//GEN-END:variables

    private void formatRows() {

        DefaultTableModel model = (DefaultTableModel) tblGameConfirmed.getModel();

        tblGameConfirmed.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = String.valueOf(model.getValueAt(row, 6));
                c.setBackground(status.equals("Pending") ? Color.WHITE : status.equals("Approved") ? Color.GREEN : Color.RED);
                return c;
            }
        });

    }
}
