/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import resort.EcoSystem;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import resort.User.User;
import resort.User.UserDirectory;
import ui.Admin.AdminHome;
import ui.Client.ClientHome;
import ui.Food.FoodHomeWelcome;
import ui.Game.GameBook;
import ui.HouseKeeping.JanitorSchedule;
import ui.Laundry.BookLaundry;
import ui.Pool.BookPool;
import ui.Transportation.Booking.BookTransportation;

/**
 *
 * @author arvin
 */
public class LoginPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private javax.swing.JSplitPane SplitPane;
    // Print the list of users
    

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(EcoSystem system, javax.swing.JSplitPane SplitPane) {
        initComponents();
        this.system = system;
        this.SplitPane = SplitPane;
    }

    public void resetData() {
        txtEUserName.setText("");
        txtEPassword.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoginUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnLoginUser.setBackground(new java.awt.Color(0, 102, 102));
        btnLoginUser.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        btnLoginUser.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginUser.setText("LOGIN ");
        btnLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginUserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USER LOGIN ");

        txtEPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEPasswordActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Images_R/paint1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtEUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEPassword, txtEUserName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(btnLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEPassword, txtEUserName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginUserActionPerformed
    
        String userName = txtEUserName.getText();
        String password = new String(txtEPassword.getPassword()); // Using getPassword() for password fields
        ArrayList<User> list = system.getUserDirectory().getUsers();

        if (isInputValid(userName, password)) {
            handleLogin(list, userName, password);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter both username and password!");
        }
    }//GEN-LAST:event_btnLoginUserActionPerformed
    private boolean isInputValid(String userName, String password) {
        return !userName.isEmpty() && !password.isEmpty();
    }

    
    private void handleLogin(ArrayList<User> list, String userName, String password) {
        for (User user : list) {
            if (userName.equalsIgnoreCase(user.getUserName()) && password.equals(user.getUserPassword())) {
                openHomePanel(user);
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Invalid username or password!");
        resetData();
    }

    
    private void openHomePanel(User currentUser) {
        switch (currentUser.getUserRole().toLowerCase()) {
            case "client":
                SplitPane.setRightComponent(new ClientHome(system, currentUser));
                break;
            case "administrator":
                SplitPane.setRightComponent(new AdminHome(system));
                break;
            case "transportation provider":
                SplitPane.setRightComponent(new BookTransportation(system));
                break;
            case "swimming pool manager":
                SplitPane.setRightComponent(new BookPool(system));
                break;
            case "food services manager":
                SplitPane.setRightComponent(new FoodHomeWelcome(system));
                break;
            case "game supervisor":
                SplitPane.setRightComponent(new GameBook(system));
                break;
            case "laundry services manager":
                SplitPane.setRightComponent(new BookLaundry(system));
                break;
            case "house keeping supervisor":
                SplitPane.setRightComponent(new JanitorSchedule(system, null)); // Pass the appropriate arguments
                break;
            default:
                JOptionPane.showMessageDialog(this, "Unsupported user role!");
                resetData();
        }
    }
    
    private void txtEPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtEPassword;
    private javax.swing.JTextField txtEUserName;
    // End of variables declaration//GEN-END:variables
}
