package ui.HouseKeeping;

import resort.EcoSystem;
import resort.HouseKeeping.HouseKeepingSchedule;
import resort.User.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arvin
 */
public class JanitorSchedule extends javax.swing.JPanel {

    /**
     * Creates new form JanitorSchedule
     */
    EcoSystem system;
    User user;

    public JanitorSchedule(EcoSystem system, User user) {
        initComponents();
        this.system = system;
        this.user = user;

        populateTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingTasksTable = new javax.swing.JTable();
        acceptTaskBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tasksProgressTables = new javax.swing.JTable();
        completeTaskBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Janitor Schedule");

        pendingTasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Room Number", "Cleaning Date", "Cleaning Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pendingTasksTable);

        acceptTaskBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        acceptTaskBtn.setForeground(new java.awt.Color(0, 102, 102));
        acceptTaskBtn.setText("Accept Task");
        acceptTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptTaskBtnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pending Tasks");

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tasks In Progress");

        tasksProgressTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Room Number", "Cleaning Date", "Cleaning Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tasksProgressTables);

        completeTaskBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        completeTaskBtn.setForeground(new java.awt.Color(0, 102, 102));
        completeTaskBtn.setText("Complete Task");
        completeTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeTaskBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(459, 459, 459)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acceptTaskBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(completeTaskBtn)))))
                .addContainerGap(461, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(acceptTaskBtn))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(completeTaskBtn)
                .addContainerGap(374, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptTaskBtnActionPerformed
        // TODO add your handling code here:

        try {
            int index = pendingTasksTable.getSelectedRow();

            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Please select a Task to be assigned to you");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) pendingTasksTable.getModel();
            String scheduleId = String.valueOf(model.getValueAt(index, 0));
            HouseKeepingSchedule selectedSchedule = system.getHouseKeepingScheduleDirectory().getScheduleById(scheduleId);

            selectedSchedule.setAssignedUser(user);
            selectedSchedule.setTaskStatus("In Progress");

            system.getHouseKeepingScheduleDirectory().updateSchedule(selectedSchedule);

            JOptionPane.showMessageDialog(this, "Task assigned to you successfully");
            populateTables();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a Task to be assigned to you");
        }
    }//GEN-LAST:event_acceptTaskBtnActionPerformed

    private void completeTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeTaskBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            int index = tasksProgressTables.getSelectedRow();

            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Please select a Task to be completed");
                return;
            }
            
            DefaultTableModel model = (DefaultTableModel) tasksProgressTables.getModel();
            String scheduleId = String.valueOf(model.getValueAt(index, 0));
            HouseKeepingSchedule selectedSchedule = system.getHouseKeepingScheduleDirectory().getScheduleById(scheduleId);
            
            selectedSchedule.setTaskStatus("Completed");

            system.getHouseKeepingScheduleDirectory().updateSchedule(selectedSchedule);

            JOptionPane.showMessageDialog(this, "Task completed successfully");
            populateTables();
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a Task to be completed");
        }
    }//GEN-LAST:event_completeTaskBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptTaskBtn;
    private javax.swing.JButton completeTaskBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pendingTasksTable;
    private javax.swing.JTable tasksProgressTables;
    // End of variables declaration//GEN-END:variables

    private void populateTables() {

        try {

            DefaultTableModel pendingModel = (DefaultTableModel) pendingTasksTable.getModel();
            DefaultTableModel progressModel = (DefaultTableModel) tasksProgressTables.getModel();
            pendingModel.setRowCount(0);
            progressModel.setRowCount(0);

            for (HouseKeepingSchedule schedule : system.getHouseKeepingScheduleDirectory().getHouseKeepingScheduleDirectory()) {

                if (schedule.getTaskStatus().equals("Pending")) {

                    Object[] pendingRow = new Object[5];
                    pendingRow[0] = schedule.getTaskID();
                    pendingRow[1] = schedule.getAssignedRoom();
                    pendingRow[2] = schedule.getScheduledDate();
                    pendingRow[3] = schedule.getScheduledTime();
                    pendingRow[4] = schedule.getTaskStatus();

                    pendingModel.addRow(pendingRow);

                } else {

                    if (schedule.getAssignedUser().getUserId().equals(user.getUserId())) {

                        Object[] progressRow = new Object[5];
                        progressRow[0] = schedule.getTaskID();
                        progressRow[1] = schedule.getAssignedRoom();
                        progressRow[2] = schedule.getScheduledDate();
                        progressRow[3] = schedule.getScheduledTime();
                        progressRow[4] = schedule.getTaskStatus();

                        progressModel.addRow(progressRow);
                    }
                }
            }

        } catch (Exception e) {

        }
    }
}
